### ISSUE TITLE
Draxlmaier - The number of jobs posted on Peviitor and the one posted on the company website isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/based_scraper_py#112]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Draxlmaier" in the search bar.
3. Check the number of jobs available for Draxlmaier.
4. Open "https://d-career.org/Draexlmaier/go/DR%C3%84XLMAIER-Job-Opportunities-in-Romania-%28Romanian%29/4196801/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 66 jobs posted on Peviitor website while on the company website there are posted 68 available jobs for Romania.

![draxlmaier peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/f1252aad-aba2-4286-93bb-8216f0234379)

![draxlmaier site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/5b53fba5-cb38-4d31-ab66-134c068d165f)

**Comment by Ale230992** [comment]
The issue is still reproducing.

![draxlmaier peviitor reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/2538541f-d567-4aeb-95e3-fe07fbb98774)

![draxlmaier site reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/5d9ec9a4-4352-47ed-bf0d-c7f65bb9137f)

**Comment by lalalaurentiu** [comment]
Do you run the scraper before testing? because my results is the same.
<img width="1440" alt="Screenshot 2023-09-26 at 07 04 25" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/5ccf715f-feb1-4e1f-9a1a-2e8eba3ce54f">
<img width="1440" alt="Screenshot 2023-09-26 at 07 04 57" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/6a9037e7-6f8f-42ad-948b-a9e69a2a2342">
<img width="1440" alt="Screenshot 2023-09-26 at 07 05 24" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/dc070a5b-1a70-4956-89eb-18269d1f18b6">

**Comment by Ale230992** [comment]
I did run it, yesterday; it appears the matter solved by itself. 

![draxlmaier scraper reverificare](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/b2aa037d-1893-4f3c-a9f3-89cac623405f)
